//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importAccountExcel.TallyDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICSRDBTALLYEntities : DbContext
    {
        public ICSRDBTALLYEntities()
            : base("name=ICSRDBTALLYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ledgers> Ledgers { get; set; }
        public DbSet<Vouchers> Vouchers { get; set; }
    }
}
