//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importAccountExcel.TallyDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public int Autoid { get; set; }
        public Nullable<decimal> TallyMasterid { get; set; }
        public string Voucherid { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string VoucherType { get; set; }
        public string LedgerName { get; set; }
        public string BillName { get; set; }
        public string CrDr { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Narration { get; set; }
        public string InstrumentNumber { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public string InstrumentType { get; set; }
        public string InstrumentBank { get; set; }
        public Nullable<System.DateTime> Adddate { get; set; }
        public string UserName { get; set; }
        public string Void { get; set; }
        public Nullable<System.DateTime> voiddate { get; set; }
        public string voidUser { get; set; }
        public string projectnumber { get; set; }
        public string oppledgername { get; set; }
        public string CostCentreName { get; set; }
    }
}
