//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importAccountExcel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTable
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public string toby { get; set; }
        public string particular { get; set; }
        public string voucherType { get; set; }
        public Nullable<int> vchno { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string AccountDetail { get; set; }
    }
}
