//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importAccountExcel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class secMstr
    {
        public int id { get; set; }
        public int mstrid { get; set; }
        public string head { get; set; }
        public string amtcheq { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<decimal> amount { get; set; }
    }
}
